on:
  workflow_call:
   inputs:
     environment:
      required: true
      type: string

jobs:
  pass-secret-to-action:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Use a repo or org secret from the calling workflow.
        run: echo ${{ secrets.CALLING_WORKFLOW_SECRET }}