on:
  workflow_call:
   inputs:
     environment:
      required: true
      type: string

jobs:
  pass-secret-to-action:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Use a repo or org secret from the calling workflow.
        if: secrets.CALLING_WORKFLOW_SECRET == 'TEST
        run: echo 'SECRET IS TEST'
      - name: Use a repo or org secret from the calling workflow.
        if: secrets.CALLING_WORKFLOW_SECRET == 'DEV'
        run: echo 'SECRET IS DEV'
