name: Production deploy

# only trigger on pull request closed events
on:
  push:
    branches:
    - 'main'

jobs:
   deploy_to_prod:
    name: 'Production deployment'
    uses: ./.github/workflows/final-main.yml
    secrets: inherit
    with:
      name: 'erandeprod'
      environment: 'prod'
