name: Customer API
on:
  push:
   paths:
     - 'api/CustomerAPI/**'
     - '.github/workflows/*'
  #Deploy to PROD on PRs to main
  pull_request:
    types: [opened]
    
jobs:
  deploy_to_prod:
    if: github.event_name =='push' && github.branch == 'main'
    name: 'PROD'
    uses: ./.github/workflows/final-main.yml
    secrets: inherit
    with:
      name: 'erandeprod'
      environment: 'prod'
  deploy_to_dev:
    if: github.branch != 'main'
    name: 'DEV'
    uses: ./.github/workflows/final-main.yml
    secrets: inherit
    with:
      name: 'erande'
      environment: ''
 
