name: Customer API
on:
  push:
   paths:
     - 'api/CustomerAPI/**'
     - '.github/workflows/*'
  pull_request:
    branches:
     - main
jobs:
  deploy_to_prod:
    if: github.event.pull_request.merged == true && github.branch == 'main'
    name: 'PROD'
    uses: ./.github/workflows/final-main.yml
    secrets: inherit
    with:
      name: 'erandeprod'
      environment: 'prod'
  deploy_to_dev:
    if: github.branch != 'main' && github.event_type =='push'
    name: 'DEV'
    uses: ./.github/workflows/final-main.yml
    secrets: inherit
    with:
      name: 'erande'
      environment: ''
 